### ISSUE TITLE
Models specification

### ISSUE THREAD

**Issue by tressoldi** [FBartos/RoBMA#10]
Is it possible to specify the type of model instead of the simple list of them (see attached plot)?
![RoBMA](https://user-images.githubusercontent.com/11275642/125649209-1ebf4e4a-9b1e-4e64-adb4-b162b803534d.png)

Thanks
Patrizio

**Comment by FBartos** [comment]
Hi Patrizio,
I'm not completely sure what do you mean by that. Do you want to show only a particular subset of the models in the figure?

**Comment by tressoldi** [comment]
No, I'd like to know to what type of model (e.g. random model null effect, random model with heterogeneity, etc.) model 19, 20, etc. refer to.

**Comment by FBartos** [comment]
Oh, I see. The previous version used to show that information in the figure, but the default 36 model ensemble makes it impossible to plot all information.

To find out what number refers to which model, you can use the summary function. Assuming that you fitted the models into a `fit` object, e.g., ` fit <- RoBMA(....)`, you can print a detailed summary of the fitted models with:
```summary(fit, type = "models")```

**Comment by tressoldi** [comment]
OK. I'll try it.
I have another question. 
How is it possible to test only some models e.g. only random effects, based on theoretical or empirical reasons?

**Comment by FBartos** [comment]
Good, hope it helps. 

Regarding the specification of different types of models, you can remove fixed-effect models by specifying: `fit <- RoBMA(..., priors_heterogeneity_null = NULL)` argument.
More information and examples are described in the vignettes:
https://fbartos.github.io/RoBMA/articles/ReproducingBMA.html
https://fbartos.github.io/RoBMA/articles/CustomEnsembles.html

**Comment by tressoldi** [comment]
Many thanks.
Patrizio

**Comment by FBartos** [comment]
Glad it helped.
Best,
Frantisek
