### ISSUE TITLE
prior_informed("van Erp") - help file example is producing an error

### ISSUE THREAD

**Issue by shanelindsay** [FBartos/RoBMA#16]
RoBMA_2.1.1    
https://rdrr.io/cran/RoBMA/man/prior_informed.html

Help file example is producing an error:

> p1 <- prior_informed("van Erp")
> p1
Error in switch(family, norm = paste0("mean=", param[1], ", sd=", param[2]),  : 
  EXPR must be a length 1 vector

**Comment by FBartos** [comment]
Hi @shanelindsay ,

Thanks for reporting the issue! I installed the CRAN version of the package (2.1.1) but I couldn't reproduce the error. Could you please let me know what OS and R-version are you using?

Cheers,
Frantisek

**Comment by shanelindsay** [comment]
Windows 10, R version 4.0.3 (2020-10-10)
Seeing that date makes me feel like I might be due for an upgrade.
I did manage to "Oosterwijk prior" from reading about the settings, i.e.
prior("t", c(location = 0.35, scale = 0.102, nu = 3), lower = 0)

**Comment by FBartos** [comment]
This is very weird. I reinstalled the R 4.0.3 version and could not reproduce the error. Could you try reinstalling the `BayesTools` and `RoBMA` R packages to check whether it helps?

```
install.packages("BayesTools")
install.packages("RoBMA")
```

Cheers,
Frantisek
