### ISSUE TITLE
Typo in vignette

### ISSUE THREAD

**Issue by ghost** [FBartos/RoBMA#32]
It looks like

> and inverse-gamma distribution with scale = 1 and shape 0.15 for the heterogeneity parameter

at 

https://github.com/FBartos/RoBMA/blob/8de6009b50670276efcaf65f4a9dd69b5f432fa3/vignettes/ReproducingBMA.Rmd#L76C13-L76C13

has to be

> and inverse-gamma distribution with shape = 1 and scale = 0.15 for the heterogeneity parameter

when you look at the specification at

https://github.com/FBartos/RoBMA/blob/8de6009b50670276efcaf65f4a9dd69b5f432fa3/vignettes/ReproducingBMA.Rmd#L117C71-L117C71

**Comment by FBartos** [comment]
Thanks! There is indeed a typo in the text -- I will fix that with the next version.
