### ISSUE TITLE
Error in Loading about runjags

### ISSUE THREAD

**Issue by ciuhkimo** [FBartos/RoBMA#6]
When I just tried to using library(RoBMA), the message shows: 

Loading required namespace: runjags
Please, note the following changes in version 1.2.0 (see NEWS for more details):
- all models are now estimated using the likelihood of effects sizes (instead of t-statistics)
- parametrization of random effect models changed (the studies' true effects are marginalized out of the likelihood)
Warning message:
In value[[3L]](cond) :
  The RoBMA module couldn't be loaded from /Library/Frameworks/R.framework/Versions/4.0/Resources/library/RoBMA/libs. libname: /Library/Frameworks/R.framework/Versions/4.0/Resources/library, pkgname: RoBMA.

I have no idea about what's wrong with my coding. I just use the R 4.0.5 with RStudio under arm system M1 MacBook.

**Comment by FBartos** [comment]
Hi @ciuhkimo,

thanks for reporting the bug. Could you check whether you have JAGs installed on your laptop?

For example by running this rjags snippet:
```
library(rjags)
data(LINE)
LINE$recompile()
LINE.samples <- jags.samples(LINE, c("alpha","beta","sigma"),
                             n.iter=1000)
LINE.samples
```

Cheers,
Frantisek

**Comment by ciuhkimo** [comment]
> Hi @ciuhkimo,
> 
> thanks for reporting the bug. Could you check whether you have JAGs installed on your laptop?
> 
> For example by running this rjags snippet:
> 
> ```
> library(rjags)
> data(LINE)
> LINE$recompile()
> LINE.samples <- jags.samples(LINE, c("alpha","beta","sigma"),
>                              n.iter=1000)
> LINE.samples
> ```
> 
> Cheers,
> Frantisek

Thank you! I found I haven't installed JAGs on my laptop.

**Comment by FBartos** [comment]
Awesome, thanks for letting me know!
